Update deploy-mudx-nuget.yml
Signed-off-by: Versile Johnson II <148913404+versile2@users.noreply.github.com>

diff --git a/.github/workflows/deploy-mudx-nuget.yml b/.github/workflows/deploy-mudx-nuget.yml
--- a/.github/workflows/deploy-mudx-nuget.yml
+++ b/.github/workflows/deploy-mudx-nuget.yml
@@ -92,15 +92,6 @@ jobs:
           $files = @("mudx.min.css", "mudx.min.js", "prism.js", "mudxProvider.js")
           $nupkg = Get-ChildItem ./src/MudX/nupkgs/*.nupkg | Where-Object { $_.Name -notlike "*.symbols.nupkg" } | Select-Object -First 1
           ./tools/CheckStaticAssets.ps1 $nupkg.FullName $files
-         
-      - name: Publish NuGet package
-        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
-        working-directory: ./src/MudX
-
-      - name: Push Symbol package
-        run: |
-          dotnet nuget push nupkgs/*.snupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate || echo "Symbol package upload failed, but continuing."
-        working-directory: ./src/MudX
 
       - name: Create GitHub release
         env:
@@ -112,6 +103,15 @@ jobs:
             --generate-notes \
             ./src/MudX/nupkgs/*.nupkg \
             ./src/MudX/nupkgs/*.snupkg
+         
+      - name: Publish NuGet package
+        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
+        working-directory: ./src/MudX
+
+      - name: Push Symbol package
+        run: |
+          dotnet nuget push nupkgs/*.snupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate || echo "Symbol package upload failed, but continuing."
+        working-directory: ./src/MudX
 
       - name: Show updated csproj version
         run: grep '<Version>' ./src/MudX/MudX.csproj
